### ISSUE TITLE
[Page error]: https://piscinadeentropia.es/ciberseguridad/ciberseguridad_intro/

### ISSUE THREAD

**Issue by antoniohernan** [Isaaker/piscinadeentropia#10]
### Contact Details

antonio.hernan@gmail.com

### What happened?

El enlace a la imagen de Mitnick no funciona.
Parece que trata de cargar la imagen de otra ruta, o que trata de cargar a imagen en minusculas.

### Error URL

https://piscinadeentropia.es/ciberseguridad/ciberseguridad_intro/

### Browser

Firefox

### Browser Version

y yo que se, la del banco

### Operative System (OS)

Windows (Microsoft)

### OS Version

puaf.. ni idea

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I read the avaible Documentation
- [X] I have checked that there is no issue on the same subject
- [X] I have checked that my issue does not contain any relevant security data (Passwords, Secrets or Users)
- [X] I have checked that my issue is not a Security Vulneability [Security Policy](https://github.com/Isaaker/Ghost_Simulator_ES/blob/main/SECURITY.md)

**Comment by Isaaker** [comment]
Gracias por la issue, he arreglado el problema (aunque he tenido unos problemas con el commit y he enlazado mal la issue) y ya se puede visualizar la página [https://piscinadeentropia.es/ciberseguridad/ciberseguridad_intro/](https://piscinadeentropia.es/ciberseguridad/ciberseguridad_intro/) de forma correcta.

El problema radicaba en la ruta de la imagen, que no había sido correctamente escrita y daba lugar a un error 404.

Sin más particular, te agradezco de nuevo tu aportación.
